Adding load method for playback pattern creation
clappr/hlsjs-playback pull request #39
Opened 2023-03-06 02:06 UTC by leaofelipe

## Summary

This PR adds a Load method, implementing a pattern for Clappr playbacks.

## How to test

1. Run the project
2. Loads another media using the new load method.
3. The video should be played correctly.

2023-03-09 17:21 UTC, cristiano-soares approved these changes

2023-03-14 16:48 UTC, kurisosan approved these changes

2023-03-14 16:48 UTC, cristiano-soares commented on src/hls.js
> +    let extrapolatedEndTime = (correlation.remote + timePassed) / 1000
How about we use `const` here instead of `let`?

2023-03-14 16:48 UTC, cristiano-soares commented on src/hls.test.js
> +      expect(playback._hls.loadSource).toHaveBeenCalledWith(url)
How about adding the following line in order to ensure that the method has been called only once?
`expect(playback._hls.loadSource).toHaveBeenCalledTimes(1)`

2023-03-16 14:03 UTC, leaofelipe commented on src/hls.test.js
> +      expect(playback._hls.loadSource).toHaveBeenCalledWith(url)
That's a good issue, but it's not very useful in this case, since I only call the trigger only once  👍🏻

2023-05-17 20:40 UTC, jhonatangcavalcanti requested changes

2023-05-17 20:40 UTC, jhonatangcavalcanti commented on src/hls.js
> +  }
```suggestion
    this._hls.destroy()
    this._hls = null
  }
```

2023-05-17 21:11 UTC, jhonatangcavalcanti approved these changes

2023-05-17 21:11 UTC, merged